name: Build & Publish Android package
on:
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Download dependencies
      run: ./gradlew build --no-daemon

    - name: Build Library
      run: ./gradlew assembleRelease --no-daemon

    - name: Publish to GitHub Packages
      env:
        GITHUB_ACTOR: ${{ secrets.USER_ID }}
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: ./gradlew publish
