name: Build & Publish Android package
on:
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Build started
      run: |
        echo "Workflow started."
        echo "Checking out code."

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo Setting up JDK 17
      run: echo "Setting up JDK 17."

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Build project
      run: |
        echo "Building the project."
        ./gradlew build --no-daemon

    - name: Build Library
      run: |
        echo "Building release AAR."
        ./gradlew assembleRelease --no-daemon

    - name: Publish to GitHub Packages
      env:
        GITHUB_ACTOR: ${{ secrets.USER_ID }}
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        echo "Publishing to GitHub Packages."
        ./gradlew publish
        echo "Publish to GitHub Packages complete."

    - name: Echo finish
      run: echo "Workflow completed."
